'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const root = path.join(__dirname, '..');
const result = spawnSync('cargo', ['build', '--release', '--locked', '--bin', 'sanc'], { cwd: root, stdio: 'inherit' });
if (result.error || result.status !== 0) process.exit(result.status || 1);
const name = process.platform === 'win32' ? 'sanc.exe' : 'sanc';
fs.mkdirSync(path.join(root, 'native'), { recursive: true });
const executable = path.join(root, 'native', name);
fs.copyFileSync(path.join(root, 'target', 'release', name), executable);
fs.chmodSync(executable, 0o755);
const manifest = { platform: process.platform, arch: process.arch, sha256: crypto.createHash('sha256').update(fs.readFileSync(executable)).digest('hex') };
fs.writeFileSync(path.join(root, 'native', 'manifest.json'), JSON.stringify(manifest) + '\n');
console.log(`Built local preview for ${manifest.platform}-${manifest.arch}`);
